name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend
        run: |
          docker build -t hesam009/frontend:latest ./frontend
          docker push hesam009/frontend:latest

      - name: Build & Push Backend
        run: |
          docker build -t hesam009/backend:latest ./backend
          docker push hesam009/backend:latest
