name: Build and Test (Docker + Node.js)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Install dependencies and test backend
      - name: Install and test backend
        run: |
          cd backend
          npm install
          npm test || echo "No test script found"

      # Step 4: Install dependencies and test frontend
      - name: Install and test frontend
        run: |
          cd frontend
          npm install
          npm test || echo "No test script found"

      # Step 5: Build Docker images
      - name: Build Docker images
        run: |
          docker compose build

      # Step 6: List images (for verification)
      - name: Verify Docker images
        run: docker images
      # Step 7: Login & push to Docker Hub
      - name: Push Docker images to Docker Hub
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag fusionpact-frontend $DOCKER_USERNAME/fusionpact-frontend:latest
          docker tag fusionpact-backend $DOCKER_USERNAME/fusionpact-backend:latest
          docker push $DOCKER_USERNAME/fusionpact-frontend:latest
          docker push $DOCKER_USERNAME/fusionpact-backend:latest

