name: Build, Test, and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Install dependencies and test backend
      - name: Install and test backend
        run: |
          cd backend
          npm install
          npm test || echo "No backend test script found"

      # Step 4: Install dependencies and test frontend
      - name: Install and test frontend
        run: |
          cd frontend
          npm install
          npm test || echo "No frontend test script found"

      # Step 5: Build Docker images
      - name: Build Docker images
        run: |
          docker compose build

      # Step 6: Login to Docker Hub
      - name: Docker Hub Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 7: Tag and Push images
      - name: Push Docker images to Docker Hub
        run: |
          docker tag fusionpact-devops-challenge-frontend ${{ secrets.DOCKER_USERNAME }}/fusionpact-frontend:latest
          docker tag fusionpact-devops-challenge-backend ${{ secrets.DOCKER_USERNAME }}/fusionpact-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fusionpact-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fusionpact-backend:latest

      # Step 8: Verify pushed images
      - name: Confirm Docker push
        run: docker images
